### ISSUE TITLE
Automatic recompute of Links (ArchWindow, ArchEquipment) after creation

### ISSUE THREAD

**Issue by balrobs** [paullee0/FreeCAD_SketchArch#6]
If users forget to start a recompute after creating Archwindow and ArchEquipment Links the attach command sometimes gives un unexpected result!
See Forum discussion:
[https://forum.freecadweb.org/viewtopic.php?f=23&t=50802&start=110#p469507](url)

**Comment by paullee0** [comment]
Details of what happens - 
1. After creating the Link, the system has not recomputed it (there is a mark indicating recompute is pending)
2. The appLinkExecute() which includes setPropertiesLinkCommon() to add Hosts property is thus not run
3. When the AttachToEdge tool is used, it thus set the Hosts[0] of the Linked Object, instead of the Link's new Hosts[0], to the new target Object to Attach, thus wrong

Solution - 
1. Either the FC should not postpone the recompute() of a Link, or
2. AttachToEdge tool check if it is a Link Object, and if the Link.State list includes "Touched", make it recompute()

**Comment by paullee0** [comment]
Commit to fix the problem
2ca3698ffffd23e2779dfbf929383f405026316f

Hope more peoples can test if it works :D
